apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-psp-role
  namespace: system
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - custom-psp
  verbs:
  - use
