name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install docker
      uses: docker-practice/actions-setup-docker@master
      
    - name: Create k8s Kind Cluster
      env:
          VERTICA_CE_URL: "https://vertica-community-edition-for-testing.s3.amazonaws.com/XCz9cp7m/vertica-10.1.1-0.x86_64.RHEL6.rpm"
      run: |
        curl -O https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubectx
        curl $VERTICA_CE_URL -o vertica-x86_64.RHEL6.latest.rpm
        scripts/run-k8s-int-tests.sh

    - name: Test
      run: echo "done"
