name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Create k8s Kind Cluster
      run: |
        scripts/kind.sh init cluster1
        apt install kubectx
        scripts/setup-int-tests.sh

    - name: Test
      run: echo "done"
