name: Scorecard tests

on: [push, pull_request]

jobs:

  sct:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install kubectl
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client
        
    - name: Download operator-sdk
      run: |
        mkdir $(pwd)/bin
        make bundle

    - name: Run scorecard tests
      run: bin/operator-sdk scorecard bundle
