name: Scorecard tests

on: [push, pull_request]

jobs:

  sct:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    
    - name: Install kubectx   
      shell: bash
      env:
          KUBECTX_URL: https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubectx
      run: |
        curl -fsSLO $KUBECTX_URL
        chmod +x kubectx
        sudo install -o root -g root -m 0755 kubectx /usr/local/bin/kubectx
        
    - name: Create kind cluster
      run: |
        echo "Setting up kind cluster named vertica"
        scripts/kind.sh  init vertica
        kubectx kind-vertica

    - name: Run scorecard tests
      run: make scorecard-tests