name: Scorecard tests

on: [push, pull_request]

jobs:

  sct:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download operator-sdk
      run: |
        ls .
        make operator-sdk

    - name: Run scorecard tests
      run: bin/operator-sdk scorecard bundle
